@host = http://localhost
@listId = 1
@ownerId = 1
@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3NjQ1MDQ0MzUsImV4cCI6MTc2NDUwODAzNSwicm9sZXMiOlsiUk9MRV9VU0VSIl0sImVtYWlsIjoidGVzdEBleGFtcGxlLmNvbSJ9.JJE1o5TFZrWz5VEz4Fqfovtoehtimnmj1l2bUEkI2TPhM-uml5hX5R9StHdcqjAB9FOC3kIiDYfuXpt74ZqWysinJU1YwdefugDbaftkjjYsN0MxpaiUCdRBy3a7jOf5qkZoUktnPX7uT42-NPK1RN_Ns-oVssCzYf_TVtjWUSRNhf7bKp_vH2pPm6MT_Vt0rCS78f-JDN1FV99DiDAIoZTj3tFsH0-3BHuRMMVqiySsGkycupMv-JL1yhcZ0FiNyfYLlOx8b_Ad9PKxy5rlmgn_wym44SfRVv9Jes_DGsU6ka3Y_qIrRzTnsyk0GTl73M1I5XJKJiyiIKk-ysTGDPponckKv9_Wm05LSGMYLxvjYedE76fxZT9mUytIuvj4Wv7GfTBbnuuTPEQcqmzgsCpdpsh-xJseBZ7P-l8htu85Hb1pA9kGJHKhPHBoQHSg4iVNRvaR75-fY0zq7kamaBDOUzOUS57fTysan2j_3TYpTH1CNrRO4ncAvRG1sVEZy4oLE_CoF9-hRXcL_Rhs2dpqce6lMK4YWgTjncdOPdvQJzQeOdr_5XsqajdXONuUEQ1igJeN01UGNzovsKi5UpQ57BWp4N0KsRmN1kfq_N9lMspSyaXCBA6NtMcVL22UAe0OfOSoLC4HYwT1QxJ9fa2Gf6-xm9ZqRwqj4HnGBHk
@refresh_token = de770e620114ae3df9e7fda5fca50d5701800e718de3f3025827dadde8d59d36caad64764e63d31a87fccdf751a1f020b1dd6d9b3c9a8223bce54b80930529b6



# Bejelentkezés (Token Szerzés)
POST http://localhost/api/login_check
Content-Type: application/json

{
    "email": "test@example.com",
    "password": "tesztjelszo"
}

###


# Jogosultság Ellenőrzés
GET {{host}}/api/shopping_lists/{{listId}}
Authorization: Bearer {{token}}

###


# Refresh Token Használata (Új JWT szerzése)
POST {{host}}/api/token/refresh
Content-Type: application/json

{
    "refresh_token": "{{refresh_token}}"
}

###


# Lista létrehozása (POST /api/shopping_lists)
POST {{host}}/api/shopping_lists
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Másik lista"
}

###


# Hitelesített Kérés (Listák Lekérdezése)
GET {{host}}/api/shopping_lists
Authorization: Bearer {{token}}

###


# Az össes item lekérdezése
GET  {{host}}/api/shopping_list_items
Authorization: Bearer {{token}}

###


# Hitelesített Kérés (item Lekérdezése)
GET {{host}}/api/shopping_list_items/1
Authorization: Bearer {{token}}

###


# Tétel hozzáadása egy listához (POST /api/shopping_lists/{listId}/shopping_list_items)
POST {{host}}/api/shopping_lists/6/shopping_list_items
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Csipsz",
    "quantity": "3 cs"
}

###


# Tétel készre jelölése (PATCH /api/shopping_list_items/{id})
PATCH {{host}}/api/shopping_list_items/5
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "isCompleted": true
}

###


# Item törlése (DELETE /api/lists/{id})
DELETE {{host}}/api/shopping_list_items/3
Authorization: Bearer {{token}}
Accept: application/json

###


# Lista törlése (DELETE /api/lists/{id})
DELETE {{host}}/api/shopping_lists/6
Authorization: Bearer {{token}}
Accept: application/json

###
