@host = http://localhost
@listId = 1
@ownerId = 1
@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3NjQ1MDA4MTgsImV4cCI6MTc2NDUwNDQxOCwicm9sZXMiOlsiUk9MRV9VU0VSIl0sImVtYWlsIjoidGVzdEBleGFtcGxlLmNvbSJ9.gjz68TShAJfmy-3W47JaziRBP76YWUxp8npduqJsnkG1opQOKR-N1n4tmLl3RvQWvRJpL-8bXrIVOn77N2RNKIjS7cWIDPmirB7xKJ2Z52lxeZS1lSOLx_t_dZDXLuOSIuYHX8i6wbwvPNE-jVRfzkUqnLO8_6vVHdz8fkCS4lNklAOTP5NaNOqiQHVZJ_H6VpdUjvmTO0WVaZ9fK-EpP_GZfR_9Y2AZ5-Z_Q-ksC8GRVJKrqMdoiMlhSQndl8zZfPAa8zasjQErTY1LiqqJ03MuEr0oOYN49iVGKCUgqz9vCtQXQEuBwBGkRTS5oOG_fiQxohpsQIdTXUrK1b0qi8QhduLkSH597oJ4LdDe8WbHVkNTsjm47-LngKemxMTmzVE7msEddAQGxnw-3lrpeloaEul3uimvTuQNIe9aq39YZEhcIl2EO89ss4wT49hNDCxVkQqa5QyK0XB8KrIVZS-OvQTW5RAND5RglReHf0lan3cGWW-6ajx9GKfp01priB-hEtOzom6IFI-6zKmA7y-dlU3N2TJ1YMbpamJCpNljZJ9JKkXuckpV5Uck3_-3GN7wJXVz_hOL6Vucj8ysdH2yqMlpM53aO6TEQpQzGL-wfeqtbCo_20LLRvlMZgERTGjwKi39u0myxBCW2wjaaerc1hvtmBw9C3npCML8uGc



# Bejelentkezés (Token Szerzés)
POST http://localhost/api/login_check
Content-Type: application/json

{
    "email": "test@example.com",
    "password": "tesztjelszo"
}

###


# Lista létrehozása (POST /api/shopping_lists)
POST {{host}}/api/shopping_lists
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "Másik lista"
}

###


# Hitelesített Kérés (Listák Lekérdezése)
GET {{host}}/api/shopping_lists
Authorization: Bearer {{token}}
Accept: application/json

###


# Az össes item lekérdezése
GET  {{host}}/api/shopping_list_items
Authorization: Bearer {{token}}
Accept: application/json

###


# Hitelesített Kérés (item Lekérdezése)
GET {{host}}/api/shopping_list_items/1
Authorization: Bearer {{token}}
Accept: application/json

###


# Tétel hozzáadása egy listához (POST /api/shopping_lists/{listId}/shopping_list_items)
POST {{host}}/api/shopping_lists/6/shopping_list_items
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "Csipsz",
    "quantity": "3 cs"
}

###


# Tétel készre jelölése (PATCH /api/shopping_list_items/{id})
PATCH {{host}}/api/shopping_list_items/5
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "isCompleted": true
}

###


# Item törlése (DELETE /api/lists/{id})
DELETE {{host}}/api/shopping_list_items/3
Authorization: Bearer {{token}}
Accept: application/json

###


# Lista törlése (DELETE /api/lists/{id})
DELETE {{host}}/api/shopping_lists/6
Authorization: Bearer {{token}}
Accept: application/json

###
